// Package bgmidmap embeds the vendored AniList->Bangumi id map (generated by
// cmd/bgmmap from Fribb x BangumiExtLinker, joined on MAL id) and seeds it
// into the bgm_id_map table at boot. Embedding means the binary carries the
// map — no runtime file or network dependency. The Phase-1 enrichment worker
// consults bgm_id_map before any Bangumi search to bind mainstream titles
// authoritatively instead of fuzzy-matching.
package bgmidmap

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	dbgen "github.com/lawrenceli0228/animego/go-api/internal/db/gen"
)

//go:embed anilist_bgm_map.json
var rawMap []byte

// Entry mirrors one record in anilist_bgm_map.json (cmd/bgmmap MapEntry).
type Entry struct {
	AnilistID int32  `json:"anilist_id"`
	BgmID     int32  `json:"bgm_id"`
	MalID     int32  `json:"mal_id"`   // 0 when the join used the anidb fallback
	AnidbID   int32  `json:"anidb_id"` // 0 when Fribb listed no anidb_id; feeds AnimeTosho aid lookup
	Source    string `json:"source"`
}

// Load parses the embedded map. Exposed (and unit-tested) so the embed path
// + JSON shape are guarded independently of any database.
func Load() ([]Entry, error) {
	var entries []Entry
	if err := json.Unmarshal(rawMap, &entries); err != nil {
		return nil, fmt.Errorf("bgmidmap: parse embedded map: %w", err)
	}
	return entries, nil
}

// Seed full-replaces bgm_id_map from the embedded artifact inside a single
// transaction (TRUNCATE + COPY), so concurrent readers never observe an
// empty table and a refreshed map that dropped entries doesn't leave stale
// rows. Idempotent; returns the number of rows loaded.
func Seed(ctx context.Context, pool *pgxpool.Pool) (int, error) {
	entries, err := Load()
	if err != nil {
		return 0, err
	}
	if len(entries) == 0 {
		return 0, nil
	}

	rows := make([]dbgen.InsertBgmIdMapCopyParams, len(entries))
	for i, e := range entries {
		var malID *int32
		if e.MalID != 0 {
			m := e.MalID
			malID = &m
		}
		var anidbID *int32
		if e.AnidbID != 0 {
			a := e.AnidbID
			anidbID = &a
		}
		rows[i] = dbgen.InsertBgmIdMapCopyParams{
			AnilistID: e.AnilistID,
			BgmID:     e.BgmID,
			MalID:     malID,
			AnidbID:   anidbID,
			Source:    e.Source,
		}
	}

	tx, err := pool.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("bgmidmap: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := dbgen.New(tx)
	if err := q.TruncateBgmIdMap(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: truncate: %w", err)
	}
	if _, err := q.InsertBgmIdMapCopy(ctx, rows); err != nil {
		return 0, fmt.Errorf("bgmidmap: copy %d rows: %w", len(rows), err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: commit: %w", err)
	}
	return len(rows), nil
}
