// Package bgmidmap embeds the vendored AniList->Bangumi id map (generated by
// cmd/bgmmap from Fribb x BangumiExtLinker, joined on MAL and AniDB ids) and
// seeds it into the bgm_id_map table at boot. Embedding means the binary
// carries the map — no runtime file or network dependency. The Phase-1
// enrichment worker consults bgm_id_map before any Bangumi search to bind
// mainstream titles authoritatively instead of fuzzy-matching.
//
// It also embeds the AniList->AniDB pairs (Fribb alone) and seeds them into
// anidb_id_map, which the magnet handler reads for the AnimeTosho feed.
package bgmidmap

import (
	"context"
	_ "embed"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	dbgen "github.com/lawrenceli0228/animego/go-api/internal/db/gen"
)

//go:embed anilist_bgm_map.json
var rawMap []byte

//go:embed anilist_anidb_map.json
var rawAnidbMap []byte

// Entry mirrors one record in anilist_bgm_map.json (cmd/bgmmap MapEntry).
type Entry struct {
	AnilistID int32  `json:"anilist_id"`
	BgmID     int32  `json:"bgm_id"`
	MalID     int32  `json:"mal_id"`   // 0 when the join went through AniDB, or for an override
	AnidbID   int32  `json:"anidb_id"` // 0 when Fribb listed no anidb_id; feeds AnimeTosho aid lookup
	Source    string `json:"source"`
}

// Load parses the embedded map. Exposed (and unit-tested) so the embed path
// + JSON shape are guarded independently of any database.
func Load() ([]Entry, error) {
	var entries []Entry
	if err := json.Unmarshal(rawMap, &entries); err != nil {
		return nil, fmt.Errorf("bgmidmap: parse embedded map: %w", err)
	}
	return entries, nil
}

// Seed full-replaces bgm_id_map from the embedded artifact inside a single
// transaction (TRUNCATE + COPY), so concurrent readers never observe an
// empty table and a refreshed map that dropped entries doesn't leave stale
// rows. Idempotent; returns the number of rows loaded.
func Seed(ctx context.Context, pool *pgxpool.Pool) (int, error) {
	entries, err := Load()
	if err != nil {
		return 0, err
	}
	if len(entries) == 0 {
		return 0, nil
	}

	rows := make([]dbgen.InsertBgmIdMapCopyParams, len(entries))
	for i, e := range entries {
		var malID *int32
		if e.MalID != 0 {
			m := e.MalID
			malID = &m
		}
		var anidbID *int32
		if e.AnidbID != 0 {
			a := e.AnidbID
			anidbID = &a
		}
		rows[i] = dbgen.InsertBgmIdMapCopyParams{
			AnilistID: e.AnilistID,
			BgmID:     e.BgmID,
			MalID:     malID,
			AnidbID:   anidbID,
			Source:    e.Source,
		}
	}

	tx, err := pool.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("bgmidmap: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := dbgen.New(tx)
	if err := q.TruncateBgmIdMap(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: truncate: %w", err)
	}
	if _, err := q.InsertBgmIdMapCopy(ctx, rows); err != nil {
		return 0, fmt.Errorf("bgmidmap: copy %d rows: %w", len(rows), err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: commit: %w", err)
	}
	return len(rows), nil
}

// AnidbEntry mirrors one record in anilist_anidb_map.json (cmd/bgmmap
// AnidbEntry).
type AnidbEntry struct {
	AnilistID int32 `json:"anilist_id"`
	AnidbID   int32 `json:"anidb_id"`
}

// LoadAnidb parses the embedded AniList->AniDB pairs.
func LoadAnidb() ([]AnidbEntry, error) {
	var entries []AnidbEntry
	if err := json.Unmarshal(rawAnidbMap, &entries); err != nil {
		return nil, fmt.Errorf("bgmidmap: parse embedded anidb map: %w", err)
	}
	return entries, nil
}

// SeedAnidb full-replaces anidb_id_map from the embedded pairs, with the same
// single-transaction TRUNCATE + COPY as Seed.  Separate from Seed so a failure
// in one table (say, a build running before migration 0041) cannot keep the
// other from loading.  Idempotent; returns the number of rows loaded.
func SeedAnidb(ctx context.Context, pool *pgxpool.Pool) (int, error) {
	entries, err := LoadAnidb()
	if err != nil {
		return 0, err
	}
	if len(entries) == 0 {
		return 0, nil
	}

	rows := make([]dbgen.InsertAnidbIdMapCopyParams, len(entries))
	for i, e := range entries {
		rows[i] = dbgen.InsertAnidbIdMapCopyParams{AnilistID: e.AnilistID, AnidbID: e.AnidbID}
	}

	tx, err := pool.Begin(ctx)
	if err != nil {
		return 0, fmt.Errorf("bgmidmap: begin anidb tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	q := dbgen.New(tx)
	if err := q.TruncateAnidbIdMap(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: truncate anidb_id_map: %w", err)
	}
	if _, err := q.InsertAnidbIdMapCopy(ctx, rows); err != nil {
		return 0, fmt.Errorf("bgmidmap: copy %d anidb rows: %w", len(rows), err)
	}
	if err := tx.Commit(ctx); err != nil {
		return 0, fmt.Errorf("bgmidmap: commit anidb_id_map: %w", err)
	}
	return len(rows), nil
}
