#!/usr/bin/env node
// A lint gate for a repo that cannot pass `eslint .` today.
//
// next-app carries 88 pre-existing eslint errors across 62 files — mostly
// `@ts-nocheck` headers on the plain-JS library modules and
// `react-hooks/set-state-in-effect` in library/ and player/. Clearing that is
// a real piece of work, but it is somebody else's piece of work: bundling it
// into an unrelated feature branch would bury the feature's diff under sixty
// files of drive-by edits.
//
// So the gate ratchets instead of demanding zero. It records today's error
// count per file and fails when a file gets worse, or when a file with no
// recorded debt acquires any. Existing debt is grandfathered; new debt is
// not. Paying debt down is always allowed, and the script tells you when the
// baseline has slack so it can be tightened.
//
// Scope note: vendored code is excluded (see VENDORED). This is deliberately
// enforced here rather than in eslint.config.mjs, so that a developer running
// `bunx eslint .` by hand still sees everything — the gate narrows, the tool
// does not.
//
// Usage:
//   node scripts/ci/eslint-ratchet.mjs            check against the baseline
//   node scripts/ci/eslint-ratchet.mjs --update   rewrite the baseline
//
// Exit codes: 0 pass, 1 regression, 2 could not run eslint.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const APP_DIR = join(REPO_ROOT, "next-app");
const BASELINE_PATH = join(APP_DIR, ".eslint-baseline.json");

// Third-party code we have never edited. JASSUB is an upstream subtitle
// renderer shipped as build output, and worker.bundle.js is regenerated by
// next-app's `prebuild` script on every single build — a gate that can fail
// on a generated file is a gate that fails for reasons nobody can act on.
const VENDORED = [/^public\/jassub\//];

const isVendored = (file) => VENDORED.some((re) => re.test(file));

function runEslint() {
  // eslint exits 1 when it finds errors, which is the normal case here, so a
  // non-zero status is not itself a failure. Only an unparseable stdout is.
  let stdout;
  try {
    stdout = execFileSync("bunx", ["eslint", ".", "-f", "json"], {
      cwd: APP_DIR,
      encoding: "utf8",
      maxBuffer: 64 * 1024 * 1024,
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (err) {
    stdout = err.stdout;
    if (!stdout) {
      console.error("eslint produced no output. stderr:\n" + (err.stderr || "(none)"));
      process.exit(2);
    }
  }
  try {
    return JSON.parse(stdout);
  } catch {
    console.error("eslint output was not valid JSON:\n" + stdout.slice(0, 2000));
    process.exit(2);
  }
}

/** Error counts per repo-relative file, vendored paths dropped. */
function collect(results) {
  const counts = {};
  let warnings = 0;
  for (const result of results) {
    const file = relative(APP_DIR, result.filePath).split("\\").join("/");
    if (isVendored(file)) continue;
    const errors = result.messages.filter((m) => m.severity === 2).length;
    warnings += result.messages.length - errors;
    if (errors > 0) counts[file] = errors;
  }
  return { counts, warnings };
}

const { counts, warnings } = collect(runEslint());
const total = Object.values(counts).reduce((a, b) => a + b, 0);

if (process.argv.includes("--update")) {
  const baseline = {
    _comment:
      "Pre-existing eslint errors, grandfathered by scripts/ci/eslint-ratchet.mjs. " +
      "Never raise a number here to make CI pass — fix the code. Lowering is always welcome.",
    warningCeiling: warnings,
    files: Object.fromEntries(Object.entries(counts).sort(([a], [b]) => a.localeCompare(b))),
  };
  writeFileSync(BASELINE_PATH, JSON.stringify(baseline, null, 2) + "\n");
  console.log(`Baseline written: ${total} errors across ${Object.keys(counts).length} files, ${warnings} warnings.`);
  process.exit(0);
}

if (!existsSync(BASELINE_PATH)) {
  console.error(`No baseline at ${BASELINE_PATH}. Create one with --update.`);
  process.exit(2);
}

const baseline = JSON.parse(readFileSync(BASELINE_PATH, "utf8"));
const allowed = baseline.files ?? {};

const regressions = [];
for (const [file, count] of Object.entries(counts)) {
  const budget = allowed[file] ?? 0;
  if (count > budget) regressions.push({ file, count, budget });
}

const improvements = [];
for (const [file, budget] of Object.entries(allowed)) {
  const count = counts[file] ?? 0;
  if (count < budget) improvements.push({ file, count, budget });
}

if (regressions.length > 0) {
  console.error("New eslint errors introduced:\n");
  for (const { file, count, budget } of regressions) {
    console.error(`  ${file}: ${count} errors (baseline allows ${budget})`);
  }
  console.error(
    "\nFix them. Do not run --update to silence this: the baseline exists to " +
      "grandfather debt that predates the gate, not to absorb new debt.",
  );
  process.exit(1);
}

const ceiling = baseline.warningCeiling ?? Infinity;
if (warnings > ceiling) {
  console.error(`Warnings rose to ${warnings}, above the ${ceiling} ceiling. Fix them or justify raising it.`);
  process.exit(1);
}

console.log(`eslint ratchet OK — ${total} grandfathered errors, ${warnings}/${ceiling} warnings.`);
if (improvements.length > 0) {
  const fixed = improvements.reduce((n, i) => n + (i.budget - i.count), 0);
  console.log(`${fixed} error(s) fixed since the baseline. Run --update to lock the improvement in:`);
  for (const { file, count, budget } of improvements.slice(0, 10)) {
    console.log(`  ${file}: ${budget} -> ${count}`);
  }
}
