-- anidb_id_map.sql — queries for the vendored AniList->AniDB map.
-- Generated by cmd/bgmmap from Fribb/anime-lists, embedded via
-- internal/bgmidmap, and seeded at boot (migration 0041).

-- name: TruncateAnidbIdMap :exec
-- Full-replace seed, same reasoning as TruncateBgmIdMap: clear before COPY in
-- the same tx so a dropped pair leaves no stale row and readers never see an
-- empty table.
TRUNCATE anidb_id_map;

-- name: InsertAnidbIdMapCopy :copyfrom
-- Bulk-load via pgx CopyFrom; updated_at takes its column DEFAULT now().
INSERT INTO anidb_id_map (anilist_id, anidb_id)
VALUES ($1, $2);

-- name: CountAnidbIdMap :one
-- Boot log: how many AniList->AniDB pairs are loaded.
SELECT count(*)::bigint FROM anidb_id_map;
