-- bgm_id_map.sql — queries for the vendored AniList->Bangumi id map.
-- The map is generated by cmd/bgmmap (Fribb x BangumiExtLinker joined on
-- MAL id), embedded via internal/bgmidmap, and seeded at boot.

-- name: TruncateBgmIdMap :exec
-- Full-replace seed: clear before COPY so a refreshed map that DROPPED an
-- entry doesn't leave a stale row behind.  Runs in the same tx as the COPY
-- so the table is never observably empty to concurrent readers.
TRUNCATE bgm_id_map;

-- name: InsertBgmIdMapCopy :copyfrom
-- Bulk-load via pgx CopyFrom (one COPY for the whole map ~11k rows).
-- updated_at takes its column DEFAULT now().  anidb_id is last to match the
-- physical column order (added by migration 0013 via ALTER); pgx CopyFrom
-- binds positionally, so the generated column list must mirror that order.
INSERT INTO bgm_id_map (anilist_id, bgm_id, mal_id, source, anidb_id)
VALUES ($1, $2, $3, $4, $5);

-- name: CountBgmIdMap :one
-- Boot log + admin dashboard: how many AniList->Bangumi rows are loaded.
SELECT count(*)::bigint FROM bgm_id_map;
