package hant

// OpenCC s2twp, implemented against the vendored conversion table in
// data/hant/opencc-s2twp.txt.
//
// Why this file exists at all
// ---------------------------
// There is no maintained pure-Go OpenCC.  liuzl/gocc and
// longbridgeapp/opencc both embed their own frozen snapshot of the same
// dictionaries this repository already vendors, so depending on one would
// mean the dictionary version lives in go.sum instead of in a file anyone
// can diff.  The conversion algorithm is ~70 lines, so it lives here and
// the data stays where the other vendored datasets are.
//
// The result is deterministic and re-derivable: Convert is a pure
// function of (input, table), the table is generated by
// scripts/gen-opencc-s2twp.py from a pinned OpenCC release, and that
// script's --check mode proves the committed bytes still match.
//
// Which algorithm
// ---------------
// Upstream OpenCC (the C++ reference) converts by forward maximum match:
// at each position, take the longest dictionary key that is a prefix of
// the remaining text, emit its first value, and advance past it; on no
// match, copy one rune.  Inside a dictionary *group* the first member
// that yields a prefix match wins outright -- which is what makes the
// STPhrases entries beat the STCharacters ones.  A conversion chain runs
// each stage over the whole output of the previous stage.
//
// The `opencc` Python package is a reimplementation, not a port, and uses
// a different strategy: it finds the longest key matching *anywhere* in
// the string and recurses into the left and right remainders.  The two
// disagree on 6 of 11,084 production title_chinese values (0.05%) and 48
// of 15,912 description_cn values (0.30%) -- always on a phrase boundary,
// e.g. 魔法制造者, where upstream's left-to-right scan matches the
// identity phrase 法制 and Python's global scan reaches 制造.  This file
// follows upstream, because upstream is what "s2twp" names.
//
// Everything this file produces is written with source='opencc', which
// migration 0022's generated title_hant_seo column excludes from search
// results.  That is the safety net for the remaining error rate.

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

// openccDict is one dictionary out of the chain.
//
// entries maps a key to *all* of its alternatives.  Conversion only ever
// uses the first (upstream's DictEntry::GetDefault), but the full list is
// what makes the Simplified gate possible without a hand-written
// character list -- see simplifiedRunes in gate.go.
type openccDict struct {
	name string
	sha  string

	entries map[string][]string

	// lensByFirst[r] holds, in descending order, every key length (in
	// runes) for which this dictionary has a key starting with r.  It
	// turns the inner "try 16, then 15, then 14..." loop into "try the
	// two lengths that could possibly match", which matters because the
	// backfill runs this over every synopsis in the table.
	lensByFirst map[rune][]int
}

// openccStage is one link of the conversion chain.  A stage holds one or
// more dictionaries; the first one to match a prefix wins.
type openccStage struct {
	dicts []*openccDict
}

// Converter is a loaded conversion chain.  It is read-only after
// LoadConverter returns, so it is safe to share across goroutines.
type Converter struct {
	stages []openccStage
}

// LoadConverter parses a table written by scripts/gen-opencc-s2twp.py.
func LoadConverter(path string) (*Converter, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open opencc table: %w", err)
	}
	defer f.Close()
	c, err := parseConverter(f)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return c, nil
}

func parseConverter(r io.Reader) (*Converter, error) {
	c := &Converter{}
	var cur *openccDict

	sc := bufio.NewScanner(r)
	// Dictionary lines are short, but keep a generous buffer so a future
	// long phrase cannot silently truncate a key.
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)

	line := 0
	for sc.Scan() {
		line++
		text := sc.Text()
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}

		if text == "@group" {
			c.stages = append(c.stages, openccStage{})
			cur = nil
			continue
		}

		if strings.HasPrefix(text, "@dict ") {
			if len(c.stages) == 0 {
				return nil, fmt.Errorf("line %d: @dict before any @group", line)
			}
			fields := strings.Fields(strings.TrimPrefix(text, "@dict "))
			if len(fields) != 2 {
				return nil, fmt.Errorf("line %d: @dict wants <name> <sha256>, got %q", line, text)
			}
			cur = &openccDict{
				name:        fields[0],
				sha:         fields[1],
				entries:     make(map[string][]string),
				lensByFirst: make(map[rune][]int),
			}
			s := &c.stages[len(c.stages)-1]
			s.dicts = append(s.dicts, cur)
			continue
		}

		if cur == nil {
			return nil, fmt.Errorf("line %d: entry before any @dict", line)
		}

		key, value, ok := strings.Cut(text, "\t")
		if !ok || key == "" || value == "" {
			return nil, fmt.Errorf("line %d: want KEY<TAB>VALUE, got %q", line, text)
		}
		if _, dup := cur.entries[key]; dup {
			return nil, fmt.Errorf("line %d: %s duplicates key %q", line, cur.name, key)
		}

		// Validate each alternative, not just the value field as a whole.
		//
		// strings.Cut splits at the FIRST tab and strings.Split never
		// returns fewer than one element, so " 幹 乾" (a stray leading
		// space) and "幹\t乾" (a stray second tab) both satisfy
		// value != "" while producing an alternative that is empty or
		// carries a literal tab.  matchPrefix always emits alts[0], so an
		// empty first alternative would silently delete the matched span
		// from every string containing that key -- a data bug that reads
		// as a slightly shorter conversion rather than as a failure.
		// Loading is the only place that can still turn it into an error.
		alts := strings.Split(value, " ")
		for i, alt := range alts {
			if alt == "" {
				return nil, fmt.Errorf("line %d: %s key %q has an empty alternative at position %d (%q)",
					line, cur.name, key, i, value)
			}
			if strings.ContainsRune(alt, '\t') {
				return nil, fmt.Errorf("line %d: %s key %q has a tab inside alternative %q",
					line, cur.name, key, alt)
			}
		}

		cur.entries[key] = alts
		cur.indexKey(key)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(c.stages) == 0 {
		return nil, fmt.Errorf("no @group stages found")
	}
	for _, s := range c.stages {
		if len(s.dicts) == 0 {
			return nil, fmt.Errorf("a @group has no @dict")
		}
	}
	return c, nil
}

// indexKey records the key's length under its first rune, keeping the
// per-rune length list sorted descending so matching can stop at the
// first hit.
func (d *openccDict) indexKey(key string) {
	first := []rune(key)[0]
	n := len([]rune(key))
	lens := d.lensByFirst[first]
	for _, existing := range lens {
		if existing == n {
			return
		}
	}
	// Insertion sort, descending.  Lists are tiny (one to a handful).
	lens = append(lens, n)
	for i := len(lens) - 1; i > 0 && lens[i] > lens[i-1]; i-- {
		lens[i], lens[i-1] = lens[i-1], lens[i]
	}
	d.lensByFirst[first] = lens
}

// matchPrefix returns the default value and matched rune count for the
// longest key that prefixes rs, or ok=false.
func (d *openccDict) matchPrefix(rs []rune) (value string, n int, ok bool) {
	if len(rs) == 0 {
		return "", 0, false
	}
	for _, l := range d.lensByFirst[rs[0]] {
		if l > len(rs) {
			continue
		}
		if alts, hit := d.entries[string(rs[:l])]; hit {
			return alts[0], l, true
		}
	}
	return "", 0, false
}

// Convert runs the whole chain over s.
func (c *Converter) Convert(s string) string {
	if s == "" {
		return s
	}
	for i := range c.stages {
		s = c.stages[i].apply(s)
	}
	return s
}

func (st openccStage) apply(s string) string {
	rs := []rune(s)
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(rs); {
		matched := false
		for _, d := range st.dicts {
			if v, n, ok := d.matchPrefix(rs[i:]); ok {
				b.WriteString(v)
				i += n
				matched = true
				break
			}
		}
		if !matched {
			b.WriteRune(rs[i])
			i++
		}
	}
	return b.String()
}

// charDict returns the dictionary of single-rune entries from the first
// stage -- in the s2twp chain, STCharacters.
//
// It is found by shape rather than by filename: the Simplified→
// Traditional stage is the first one, and within it only the character
// dictionary carries one-rune keys (STPhrases has none, all 49,051 of its
// keys are two runes or longer).  Selecting on that property means the
// gate keeps working if upstream renames a file, and fails loudly if the
// chain's shape ever changes.
func (c *Converter) charDict() (*openccDict, error) {
	if len(c.stages) == 0 {
		return nil, fmt.Errorf("converter has no stages")
	}
	var found *openccDict
	for _, d := range c.stages[0].dicts {
		single := false
		for k := range d.entries {
			if len([]rune(k)) == 1 {
				single = true
				break
			}
		}
		if !single {
			continue
		}
		if found != nil {
			return nil, fmt.Errorf(
				"stage 0 has two dictionaries with single-rune keys (%s, %s); "+
					"the Simplified gate cannot tell which is the character table",
				found.name, d.name)
		}
		found = d
	}
	if found == nil {
		return nil, fmt.Errorf("stage 0 has no single-rune dictionary")
	}
	return found, nil
}
